#Quantez Merchant's makefile for project 1.

#This command deletes a client that has been compiled.
clean:
	@rm -f client
	@echo "client has been deleted."

#This command compiles a client.
client: client.c
	@gcc client.c -o client
	@echo "client has been created."
